name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Yeii you have taken one step forward to improve the functionality, We will get back to you promptly!'
        pr-message: 'Congratulations with the effort made to improve the experience of this plugin, We will review and merge'
